Repository suzuki-shunsuke/tfaction, pull requests merged in 2022-03, with the labels that each got.

#233 fix: set `shell: bash`
  release-module/action.yaml
Labels: bug

#235 feat: lint before generation
  test-module/action.yaml
  test/action.yaml
Labels: enhancement

#238 fix(test-module): remove lock file
  test-module/action.yaml
Labels: bug

#239 feat(release-module): add release note
  release-module/action.yaml
Labels: enhancement

#240 fix(create-follow-up-pr): create a label properly
  create-follow-up-pr/skip_create_pr.sh
Labels: bug

#213 docs: update JSON Schema
  schema/tfaction-root.json
Labels: documentation

#247 fix(scaffold-tfmigrate): create tfmigrate label
  scaffold-tfmigrate/action.yaml
Labels: bug

#248 fix: add newlines
  scaffold-tfmigrate/action.yaml
Labels: bug

#249 fix: add newline
  scaffold-tfmigrate/action.yaml
Labels: bug

#251 fix: set plan and apply's `-no-color` to parse error and warning
  terraform-apply/main.sh
  terraform-plan/main.sh
Labels: bug

#255 fix: Delete old plan file in GCS when terraform plan fails
  terraform-plan/main.sh
  tfmigrate-plan/main.sh
Labels: bug

#257 fix: Change condition to compare with string
  create-follow-up-pr/action.yaml
  create-scaffold-pr/action.yaml
  scaffold-module/action.yaml
  scaffold-tfmigrate/action.yaml
Labels: bug

#259 feat: Improve Terraform Module document and Release Note
  release-module/action.yaml
  scaffold-module/action.yaml
  scaffold-module/template/.terraform-docs.yml
  scaffold-module/template/docs/footer.md
  scaffold-module/template/docs/header.md
  scaffold-module/template/main.tf
Labels: enhancement

#260 feat(scaffold-module): run terraform-docs
  scaffold-module/action.yaml
Labels: enhancement
