Repository suzuki-shunsuke/tfaction, pull requests merged in 2022-07, with the labels that each got.

#421 feat: support setting environment variable
  get-target-config/dist/index.js
  get-target-config/src/index.ts
  get-target-config/src/lib.ts
Labels: enhancement

#425 fix: set github-comment's -config option
  terraform-apply/main.sh
  test-module/action.yaml
  test/action.yaml
Labels: bug

#428 docs: update JSONSchema (add envs)
  schema/tfaction-root.json
  schema/tfaction.json
Labels: documentation

#432 Fix GCS apply comment
  terraform-apply/main.sh
Labels: bug
