Repository suzuki-shunsuke/tfaction, pull requests merged in 2022-02, with the labels that each got.

#114 fix(export-aws-secrets-manager): mask secrets
  export-aws-secrets-manager/dist/index.js
  export-aws-secrets-manager/src/run.ts
Labels: bug

#115 feat(export-secrets): change configuration structure of GitHub Secrets
  docs/config.md
  export-secrets/dist/index.js
  export-secrets/src/lib.ts
Labels: enhancement, breaking change

#116 chore: update tfsec and tflint
  test/action.yaml
Labels: enhancement

#118 fix: fix invalid command: `aws s3 delete`
  terraform-plan/main.sh
  tfmigrate-plan/main.sh
Labels: bug

#119 fix: fix create-follow-up-pr
  create-follow-up-pr/main.sh
  list-targets-with-changed-files/dist/LICENSE
  list-targets-with-changed-files/dist/index.js
  list-targets-with-changed-files/package-lock.json
  list-targets-with-changed-files/package.json
  list-targets-with-changed-files/src/index.ts
Labels: bug

#121 fix(scaffold-working-dir): set TFACTION_JOB_TYPE
  scaffold-working-dir/action.yaml
Labels: bug

#122 fix(create-scaffold-pr): set TFACTION_JOB_TYPE
  create-scaffold-pr/action.yaml
Labels: bug

#123 docs: update document
  docs/config.md
Labels: documentation

#126 fix: stop checking plan file before removing plan file
  terraform-plan/main.sh
  tfmigrate-plan/main.sh
Labels: bug

#127 fix(tfmigrate-plan): fix the template file path of tfmigrate.hcl
  tfmigrate-plan/main.sh
Labels: bug

#128 feat(get-target-config): support configurating tfaction by tfaction.yaml
  docs/config.md
  get-target-config/dist/index.js
  get-target-config/src/index.ts
  get-target-config/src/lib.ts
  get-target-config/tests/aws/foo/tfaction.yaml
  get-target-config/tests/config-1.yaml
Labels: enhancement

#129 docs: add JSON Schema
  schema/tfaction-root.json
  schema/tfaction.json
Labels: documentation

#130 docs: add links to JSON Schema
  docs/config.md
Labels: documentation

#131 fix: remove some fields from jobConfig
  get-target-config/dist/index.js
  get-target-config/src/index.ts
Labels: bug

#135 docs: move document to GitHub Pages
  README.md
  docs/add-working-directory.md
  docs/auto-update-related-prs.md
  docs/build-matrix.md
  docs/config.md
  docs/conftest.md
  docs/follow-up-pr.md
  docs/plan-file.md
  docs/renovate.md
  docs/scaffold-working-dir.md
  docs/setup.md
  docs/tfmigrate.md
Labels: documentation

#136 docs: add a link to tfaction-docs
  README.md
Labels: documentation

#137 docs: fix JSON Schema
  schema/tfaction-root.json
  schema/tfaction.json
Labels: documentation

#140 fix: specify AWS_DEFAULT_REGION
  terraform-apply/action.yaml
  terraform-plan/action.yaml
  tfmigrate-plan/action.yaml
Labels: bug

#143 fix(scaffold-working-dir): fix the error of get-target-config
  create-scaffold-pr/action.yaml
  get-target-config/dist/index.js
  get-target-config/src/index.ts
  get-target-config/src/lib.ts
  scaffold-working-dir/action.yaml
Labels: bug

#145 fix(get-target-config): support scaffold-working-dir
  get-target-config/dist/index.js
  get-target-config/src/index.ts
Labels: bug

#146 fix: fix scaffold-working-dir
  get-target-config/dist/index.js
  get-target-config/src/index.ts
Labels: bug

#147 fix: skip conftest if policy isn't found
  terraform-plan/main.sh
Labels: bug

#148 docs: add a link to getting started
  README.md
Labels: documentation

#149 fix: terraform apply isn't run even if follow up pull request is merged
  list-targets-with-changed-files/action.yaml
  list-targets-with-changed-files/dist/index.js
  list-targets-with-changed-files/package-lock.json
  list-targets-with-changed-files/package.json
  list-targets-with-changed-files/src/index.ts
  list-targets/action.yaml
Labels: bug

#154 fix: fix parse error
  terraform-plan/action.yaml
Labels: bug

#155 fix: set GITHUB_TOKEN
  .github/workflows/apply.yaml
  .github/workflows/scaffold-working-directory.yaml
  .github/workflows/test.yaml
  setup/action.yaml
Labels: bug

#156 fix: use fromJSON
  .github/workflows/actionlint.yaml
  terraform-plan/action.yaml
Labels: bug

#157 fix(terraform-apply): fix if condition
  terraform-apply/action.yaml
Labels: bug

#158 feat: set pull request label "${TFACTION_TARGET}" in setup action
  setup/action.yaml
  terraform-plan/main.sh
  tfmigrate-plan/main.sh
Labels: enhancement

#159 fix: fix typo
  setup/action.yaml
Labels: bug

#160 fix: change the default behavior to keep the compatibility
  check-terraform-skip/dist/index.js
  check-terraform-skip/src/index.ts
Labels: enhancement

#161 fix: fix check-terraform-skip action's name and description
  check-terraform-skip/action.yaml
  get-global-config/dist/index.js
  get-global-config/src/index.ts
Labels: bug

#164 fix(list-taregts): add input `github_token`
  list-targets/action.yaml
Labels: bug

#165 docs(list-targets): update document
  list-targets/README.md
Labels: documentation

#171 feat: update tflint action to notify with github-comment
  test/action.yaml
Labels: enhancement

#172 feat: update tfsec action to notify with github-comment
  test/action.yaml
Labels: enhancement

#174 docs: move document to GitHub Pages
  check-terraform-skip/README.md
  create-follow-up-pr/README.md
  create-scaffold-pr/README.md
  deploy-ssh-key/README.md
  export-aws-secrets-manager/README.md
  export-secrets/README.md
  get-global-config/README.md
  get-target-config/README.md
  list-targets-with-changed-files/README.md
  list-targets/README.md
  list-working-dirs/README.md
  scaffold-working-dir/README.md
  setup/README.md
  terraform-apply/README.md
  terraform-plan/README.md
  test/README.md
  tfmigrate-apply/README.md
  tfmigrate-plan/README.md
Labels: documentation

#175 docs: update JSON Schema
  schema/tfaction-root.json
Labels: documentation

#176 fix: remove the override of template_dir
  get-target-config/dist/index.js
  get-target-config/src/index.ts
  schema/tfaction.json
Labels: bug

#178 chore: update tflint and tfsec action
  test/action.yaml
Labels: enhancement

#179 feat: add mention to follow up pull request body
  create-follow-up-pr/main.sh
Labels: enhancement

#180 fix: fix duplicated mention
  create-follow-up-pr/main.sh
Labels: bug

#185 feat(create-scaffold-pr): add mention to GITHUB_ACTOR
  create-scaffold-pr/action.yaml
Labels: enhancement

#187 feat: scaffold-tfmigrate
  scaffold-tfmigrate/action.yaml
  scaffold-tfmigrate/migration.hcl
  scaffold-tfmigrate/tfmigrate.hcl
Labels: enhancement

#188 fix: fix scaffold .tfmigrate.hcl
  scaffold-tfmigrate/action.yaml
Labels: bug

#198 fix: fix typo
  create-scaffold-pr/action.yaml
Labels: bug

#206 fix: rename output
  terraform-apply/action.yaml
  terraform-plan/action.yaml
Labels: bug

#207 feat: support skipping to create pull requests
  create-follow-up-pr/action.yaml
  create-follow-up-pr/github-comment.yaml
  create-follow-up-pr/skip_create_pr.sh
  create-scaffold-pr/action.yaml
  get-global-config/action.yaml
  get-global-config/dist/index.js
  get-global-config/src/index.ts
  scaffold-tfmigrate/action.yaml
Labels: enhancement

#209 fix: set "-R $GITHUB_REPOSITORY"
  create-follow-up-pr/skip_create_pr.sh
  create-scaffold-pr/action.yaml
  scaffold-tfmigrate/action.yaml
  scaffold-working-dir/action.yaml
Labels: bug

#210 fix: set tfmigrate label and target label
  create-follow-up-pr/action.yaml
  create-follow-up-pr/skip_create_pr.sh
  scaffold-tfmigrate/action.yaml
Labels: bug

#212 feat: improve the follow up pull request guide
  create-follow-up-pr/github-comment.yaml
Labels: enhancement

#214 feat: upload and download ci-info's output
  list-targets/action.yaml
  setup/action.yaml
Labels: enhancement

#215 fix: fix step id
  list-targets/action.yaml
Labels: bug

#218 fix: upload and download CI_INFO_TEMP_DIR
  list-targets/action.yaml
  setup/action.yaml
Labels: bug

#220 fix: follow up #219
  setup/action.yaml
Labels: bug

#222 feat: support modules
  get-global-config/action.yaml
  get-global-config/dist/index.js
  get-global-config/src/index.ts
  list-changed-modules/.nvmrc
  list-changed-modules/action.yaml
  list-changed-modules/dist/LICENSE
  list-changed-modules/dist/index.js
  list-changed-modules/package-lock.json
  list-changed-modules/package.json
  list-changed-modules/src/index.ts
  list-changed-modules/src/lib.ts
  list-changed-modules/tsconfig.json
  list-targets/action.yaml
  list-working-dirs/action.yaml
  release-module/action.yaml
  test-module/action.yaml
Labels: enhancement

#224 fix: typo
  test-module/action.yaml
Labels: bug

#225 feat: generate document by terraform-docs
  test-module/action.yaml
Labels: enhancement

#226 fix: typo
  test-module/action.yaml
Labels: bug

#227 fix: fix terraform-docs step
  test-module/action.yaml
Labels: bug

#228 feat: add scaffold-module action
  scaffold-module/action.yaml
  scaffold-module/template/.terraform-docs.yml
  scaffold-module/template/.tflint.hcl
  scaffold-module/template/.tfsec/config.yml
  scaffold-module/template/main.tf
  scaffold-module/template/outputs.tf
  scaffold-module/template/tfaction_module.yaml
  scaffold-module/template/variables.tf
Labels: enhancement

#229 fix: run aqua init
  scaffold-module/action.yaml
Labels: bug

#230 feat: validate inputs of release-module
  release-module/action.yaml
Labels: enhancement

#231 fix: skip pushing a commit in case of push event
  test-module/action.yaml
Labels: bug
