Repository suzuki-shunsuke/tfaction, pull requests merged in 2023-11, with the labels that each got.

#1272 feat: support disabling to update related pull requests per pull request by pull request label
  terraform-apply/main.sh
  tfmigrate-apply/github-comment.yaml
  tfmigrate-apply/main.sh
Labels: enhancement

#1275 feat: support merging jobs for tfmigrate and terraform
  apply/action.yaml
  list-targets-with-changed-files/action.yaml
  list-targets-with-changed-files/dist/index.js
  list-targets-with-changed-files/src/index.ts
  list-targets/action.yaml
  plan/action.yaml
Labels: enhancement

#1326 docs: remove the link to the getting started
  README.md
Labels: documentation

#1327 docs: add the section "Who uses tfaction?"
  README.md
Labels: documentation

#1331 docs: update the list
  README.md
Labels: documentation

#1332 Add Henry, Inc. to the list of usecases
  README.md
Labels: documentation

#1338 docs: Add Gunosy Inc. to who-uses-tfaction
  README.md
Labels: documentation, who-uses

#1339 docs: add a link to the discussion
  README.md
Labels: documentation

#1340 feat(scaffold-module): separate actions with generating codes and creating pull requests
  create-scaffold-module-pr/action.yaml
  scaffold-module/action.yaml
Labels: breaking change

#1341 feat(scaffold-module): require module templates
  create-scaffold-module-pr/action.yaml
  scaffold-module/action.yaml
  test-module/action.yaml
Labels: breaking change

#1343 feat: support running `terraform plan` with the `-destroy` option
  get-target-config/action.yaml
  get-target-config/dist/index.js
  get-target-config/src/index.ts
  get-target-config/src/lib.ts
  terraform-plan/action.yaml
  terraform-plan/main.sh
  test/action.yaml
Labels: enhancement

#1356 docs: Add Wantedly, Inc. to who-uses-tfaction
  README.md
Labels: documentation, who-uses
