Repository suzuki-shunsuke/tfaction, pull requests merged in 2023-09, with the labels that each got.

#1106 feat: support trivy
  get-target-config/action.yaml
  get-target-config/dist/index.js
  get-target-config/src/index.ts
  get-target-config/src/lib.ts
  test/action.yaml
Labels: enhancement

#1110 feat(test-module): support trivy and disabling linters tflint, tfsec, and trivy
  get-global-config/action.yaml
  get-global-config/dist/index.js
  get-global-config/src/index.ts
  get-target-config/action.yaml
  test-module/action.yaml
Labels: enhancement

#1111 feat: update `scaffold-module` and `scaffold-working-dir` to support scaffolding linters conditionally
  get-global-config/dist/index.js
  get-global-config/src/index.ts
  scaffold-module/action.yaml
  scaffold-working-dir/action.yaml
Labels: enhancement

#1114 fix(test-module): Fix ghcp argument to use implicitly GITHUB_TOKEN
  test-module/action.yaml
Labels: bug

#1150 feat(update-drift-issue): post a comment if CI failed and no comment was posted
  update-drift-issue/action.yaml
  update-drift-issue/post-comment.sh
Labels: enhancement

#1151 fix(update-drift-issue): set TFACTION_DRIFT_ISSUE_REPO_OWNER and TFACTION_DRIFT_ISSUE_REPO_NAME
  update-drift-issue/action.yaml
Labels: bug

#1152 fix(update-drift-issue): set TFACTION_DRIFT_ISSUE_REPO_FULLNAME
  update-drift-issue/action.yaml
Labels: bug

#1118 feat(setup): update aqua-checksums.json
  get-global-config/action.yaml
  get-global-config/dist/index.js
  get-global-config/src/index.ts
  setup/action.yaml
Labels: enhancement

#1153 fix(get-global-config): disable aqua_update_checksum_skip_push if TFACTION_DRIFT_ISSUE_NUMBER is set
  get-global-config/dist/index.js
  get-global-config/src/index.ts
Labels: bug

#1154 fix(setup): update update-checksum action
  get-global-config/dist/index.js
  get-global-config/src/index.ts
  setup/action.yaml
Labels: bug

#1156 fix(get-target-config): fix linter settings
  get-target-config/dist/index.js
  get-target-config/src/index.ts
Labels: bug

#1171 fix(update-drift-issue): skip posting a comment if drift detection is disabled
  update-drift-issue/action.yaml
Labels: bug

#1172 fix(test-module): stop running `terraform validate`
  test-module/action.yaml
Labels: bug

#1174 feat: check if the HEAD sha is latest
  list-targets/action.yaml
Labels: enhancement

#1175 feat: migrate plan files from S3 or GCS to GitHub Actions' Artifacts
  get-global-config/action.yaml
  get-global-config/dist/index.js
  get-global-config/src/index.ts
  get-target-config/action.yaml
  get-target-config/dist/index.js
  get-target-config/src/index.ts
  get-target-config/src/lib.ts
  list-targets/action.yaml
  setup/action.yaml
  terraform-apply/action.yaml
  terraform-apply/download_plan_file.sh
  terraform-apply/github-comment.yaml
  terraform-apply/main.sh
  terraform-plan/action.yaml
  terraform-plan/delete_old_plan.sh
  terraform-plan/main.sh
  terraform-plan/upload_plan.sh
  tfmigrate-plan/action.yaml
  tfmigrate-plan/main.sh
Labels: enhancement, breaking change
