Repository suzuki-shunsuke/tfaction, pull requests merged in 2024-12, with the labels that each got.

#2104 feat(test): support tflint --fix
  get-target-config/src/run.ts
  lib/src/index.ts
  test/action.yaml
Labels: enhancement

#2119 ci: test setup action
  .github/workflows/wc-create-pr-branch.yaml
  setup/test/foo/.terraform.lock.hcl
  setup/test/foo/main.tf
  setup/test/foo/tfaction.yaml
  setup/test/tfaction-root.yaml
Labels: setup/test/foo

#2121 docs: add tacoms to who-uses-tfaction
  README.md
Labels: documentation, who-uses

#2122 ci: test plan
  .github/workflows/wc-create-pr-branch.yaml
Labels: setup/test/foo, setup/test/foo/add-or-update

#2124 ci: test test action
  .github/workflows/create-pr-branch.yaml
  .github/workflows/test.yaml
  .github/workflows/wc-create-pr-branch.yaml
  .github/workflows/wc-hide-comment.yaml
  aqua-checksums.json
  aqua/github-comment.yaml
  aqua/tflint.yaml
  aqua/trivy.yaml
  setup/test/foo/.terraform.lock.hcl
  setup/test/foo/providers.tf
  setup/test/foo/terraform.tf
Labels: setup/test/foo, setup/test/foo/add-or-update

#2125 ci: test test-module
  .github/workflows/wc-create-pr-branch.yaml
  .prettierignore
  js/test/modules/foo/README.md
  js/test/modules/foo/providers.tf
  js/test/modules/foo/terraform.tf
Labels: setup/test/foo, setup/test/foo/add-or-update

#2126 ci: test actions' outputs
  .github/workflows/wc-create-pr-branch.yaml
  js/package-lock.json
  js/package.json
  js/src/index.ts
  js/src/test-action/index.ts
Labels: setup/test/foo, setup/test/foo/add-or-update

#2133 ci: test setup action using OpenTofu
  .github/workflows/wc-create-pr-branch.yaml
  aqua-checksums.json
  aqua/opentofu.yaml
  setup/test/opentofu/foo/.terraform.lock.hcl
  setup/test/opentofu/foo/main.tf
  setup/test/opentofu/foo/providers.tf
  setup/test/opentofu/foo/terraform.tf
  setup/test/opentofu/foo/tfaction.yaml
  setup/test/opentofu/tfaction-root.yaml
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo

#2134 ci: test test action using OpenTofu
  .github/workflows/wc-create-pr-branch.yaml
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo

#2135 ci: test plan using OpenTofu
  .github/workflows/wc-create-pr-branch.yaml
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update

#2136 ci: test terragrunt
  .github/workflows/wc-create-pr-branch.yaml
  aqua-checksums.json
  aqua/terragrunt.yaml
  setup/test/terragrunt/foo/.terraform.lock.hcl
  setup/test/terragrunt/foo/main.tf
  setup/test/terragrunt/foo/providers.tf
  setup/test/terragrunt/foo/terraform.tf
  setup/test/terragrunt/foo/terragrunt.hcl
  setup/test/terragrunt/foo/tfaction.yaml
  setup/test/terragrunt/tfaction-root.yaml
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2139 Fix tfplan file path issue when using Terragrunt
  terraform-plan/main.sh
Labels: bug

#2138 ci: split jobs
  .github/workflows/wc-create-pr-branch.yaml
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2147 ci: disable actions/checkout's persist-credentials using disable-checkout-persist-credentials
  .github/workflows/main.yaml
  .github/workflows/release.yaml
  .github/workflows/wc-create-pr-branch.yaml
  .github/workflows/wc-deploy-schema.yaml
  .github/workflows/wc-format.yaml
  .github/workflows/wc-ghalint.yaml
  .github/workflows/wc-hide-comment.yaml
  .github/workflows/wc-shellcheck.yaml
  .github/workflows/wc-test.yaml
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2149 chore: update deps
  aqua-checksums.json
  aqua.yaml
  aqua/node.yaml
  install/aqua-checksums.json
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2151 ci: enable persist-credentials for release
  .github/workflows/release.yaml
  ghalint.yaml
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2161 ci: add a workflow to check if commits in pull requests are verified
  .github/workflows/check-commit-signing.yaml
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2160 chore: added `secrets` input to tfaction/js
  js/action.yaml
Labels: bug

#2178 fix(test-module): remove invalid if statement
  test-module/action.yaml
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2176 feat(test-module): support tflint --fix
  get-global-config/action.yaml
  js/action.yaml
  js/src/get-global-config/index.test.ts
  js/src/get-global-config/index.ts
  js/src/test-action/index.ts
  test-module/action.yaml
Labels: enhancement, setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2179 feat(install): install reviewdog automatically
  install/aqua-checksums.json
  install/aqua/reviewdog.yaml
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2180 chore: update checksum
  aqua-checksums.json
  aqua.yaml
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2167 feat: add an action js/create-drift-issues
  .github/workflows/create-pr-branch.yaml
  .github/workflows/test.yaml
  .github/workflows/wc-create-pr-branch.yaml
  js/package-lock.json
  js/package.json
  js/src/create-drift-issues/index.ts
  js/src/lib/index.ts
  js/src/run.ts
  js/test/tfaction-root.yaml
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2189 feat: add js/get-or-create-drift-issue
  .github/workflows/wc-create-pr-branch.yaml
  js/src/get-or-create-drift-issue/index.ts
  js/src/run.ts
  js/test/tfaction-root.yaml
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2190 fix: add logs
  .github/workflows/wc-create-pr-branch.yaml
  js/src/create-drift-issues/index.ts
  js/src/test-action/index.ts
  js/test/tfaction-root.yaml
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2195 fix: check if drift detection is enabled
  js/src/create-drift-issues/index.ts
  js/src/export-aws-secrets-manager/run.ts
  js/src/export-secrets/index.ts
  js/src/get-or-create-drift-issue/index.ts
  js/src/lib/index.ts
Labels: bug, setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo
