Repository suzuki-shunsuke/tfaction, pull requests merged in 2025-01, with the labels that each got.

#2196 Enable detection of local path module updates when using Terragrunt
  .github/workflows/wc-create-pr-branch.yaml
  js/src/index.ts
  js/src/list-module-callers/index.ts
  js/src/test-action-terragrunt/index.ts
  js/test/list-module-callers/terragrunt/config_files.txt
  js/test/list-module-callers/terragrunt/module_files.txt
  setup/test/terragrunt/foo/terragrunt.hcl
  setup/test/terragrunt/module/main.tf
  setup/test/terragrunt/module/tfaction_module.yaml
Labels: enhancement

#2203 fix(list-module-callers): use actions/exec
  .github/workflows/wc-create-pr-branch.yaml
  js/src/list-module-callers/index.ts
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2243 fix: run terragrunt render-json on the directory where terragrunt.hcl exists
  aqua-checksums.json
  aqua/terraform.yaml
  js/src/list-module-callers/index.ts
Labels: bug, setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2244 fix(list-module-callers): run terragrunt via aqua exec
  js/src/list-module-callers/index.ts
Labels: bug, setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2245 fix(list-module-callers): run `aqua i -l -a` to create links
  js/src/list-module-callers/index.ts
Labels: bug, setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2246 fix(list-module-callers): check the output of terragrunt render-json
  js/src/list-module-callers/index.ts
Labels: bug, setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2248 feat: support debug mode
  create-follow-up-pr/create_commit.sh
  create-follow-up-pr/main.sh
  create-follow-up-pr/skip_create_pr.sh
  terraform-apply/download_plan_file.sh
  terraform-apply/main.sh
  terraform-docs/terraform-docs.sh
  terraform-plan/main.sh
  terraform-plan/renovate_change.sh
  tfmigrate-apply/main.sh
  tfmigrate-plan/main.sh
  update-drift-issue/post-comment.sh
Labels: enhancement, setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo

#2285 ci: use autofix.ci
  .github/workflows/autofix.yaml
  .github/workflows/close-no-template-issue.yaml
  .github/workflows/test.yaml
  .github/workflows/wc-format.yaml
  .github/workflows/wc-update-aqua-checksums-install.yaml
  .github/workflows/wc-update-aqua-checksums.yaml
  aqua-checksums.json
Labels: setup/test/foo, setup/test/foo/add-or-update, setup/test/opentofu/foo, setup/test/opentofu/foo/add-or-update, setup/test/terragrunt/foo
